// Renderiza o arquivo HTML
function doGet() {
  return HtmlService.createHtmlOutputFromFile('index')
    .setTitle('Gerador de Assinatura para Gmail');
}

// Função para obter as informações do local de trabalho e os setores
function getLocalTrabalhoInfo(localTrabalho) {
  const locais = {
    "Local 1": { // Reitoria
      logo: "https://portal.ifsuldeminas.edu.br/images/PDFs/comunicacao/logotipos/reitoria/reitoria-hor.png",
      endereco: "Av. Vicente Simões, 1.111, Nova Pouso Alegre, Pouso Alegre, MG, CEP: 37.553-465",
      site: "https://portal.ifsuldeminas.edu.br/index.php",
      telefone: "(35) 3449-6150",
      redesSociais: [
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/fb-verde.png", link: "https://www.facebook.com/IFSULDEMINAS" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/ig-verde.png", link: "https://www.instagram.com/ifsuldeminas/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/linkedin-verde.png", link: "https://www.linkedin.com/school/if-sul-de-minas/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/yt-verde.png", link: "https://www.youtube.com/@TVIFSULDEMINAS" }
      ],
      imagemFinal: "https://portal.ifsuldeminas.edu.br/images/Assinatura_Email/ass_reitoria.png",
      setores: [
        { nome: "Selecione o Setor!", site: "#" },
        { nome: "Assessoria Internacional", site: "https://portal.ifsuldeminas.edu.br/index.php/institucional-geral/126-servidores/131-servidores-assessoria-internacional" },
        { nome: "Auditoria Interna", site: "https://portal.ifsuldeminas.edu.br/index.php/institucional-geral/126-servidores/128-servidores-auditoria-interna" },
        { nome: "Corregedoria", site: "https://portal.ifsuldeminas.edu.br/index.php/institucional-geral/126-servidores/5393-servidores-da-corregedoria" },
        { nome: "DEAD", site: "https://portal.ifsuldeminas.edu.br/index.php/institucional-geral/477-diretoria-de-ensino-a-distancia" },
        { nome: "DDRI", site: "https://portal.ifsuldeminas.edu.br/index.php/pro-reitoria-desenvolvimento-institucional/equipe-desenvolvimento-institucional" },
        { nome: "DEAD", site: "https://portal.ifsuldeminas.edu.br/index.php/institucional-geral/477-diretoria-de-ensino-a-distancia" },       
        { nome: "DICOM", site: "https://portal.ifsuldeminas.edu.br/index.php/comunicacao" },
        { nome: "DTI", site: "https://portal.ifsuldeminas.edu.br/index.php/tic/equipe" },
        { nome: "Gabinete do Reitor", site: "https://portal.ifsuldeminas.edu.br/index.php/institucional-geral/3322-equipe-gabinete" },
        { nome: "Ouvidoria", site: "https://portal.ifsuldeminas.edu.br/index.php/institucional-geral/126-servidores/127-servidores-ouvidoria" },
        { nome: "Procuradoria", site: "https://portal.ifsuldeminas.edu.br/index.php/institucional-geral/126-servidores/126-servidores-procuradoria" },
        { nome: "PROAD", site: "https://portal.ifsuldeminas.edu.br/index.php/institucional-geral/126-servidores/134-servidores-proad" },
        { nome: "PROEN", site: "https://portal.ifsuldeminas.edu.br/index.php/pro-reitoria-ensino/equipe-proen" },
        { nome: "PROEX", site: "https://portal.ifsuldeminas.edu.br/index.php/pro-reitoria-extensao/equipe-proex" },
        { nome: "PPPI", site: "https://portal.ifsuldeminas.edu.br/index.php/pro-reitoria-pesquisa-pos-graduacao-inovacao/equipe-pppi" },
        { nome: "PROGEP", site: "https://portal.ifsuldeminas.edu.br/index.php/dgp/equipe-dgp" }
      ]
    },
    "Local 2": { // Carmo de Minas
      logo: "https://portal.ifsuldeminas.edu.br/images/PDFs/comunicacao/logotipos/carmodeminas/IFSULDEMINAS_Carmo-de-Minas-aplica%C3%A7%C3%B5es-horizontais-01.png",
      endereco: "Alameda Murilo Eugênio Rubião, s/n, Bairro Chacrinha, Carmo de Minas, MG, CEP: 37.472-000",
      site: "https://portal.cdm.ifsuldeminas.edu.br/",
      telefone: "(35) 99961-4276",
      redesSociais: [
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/fb-verde.png", link: "https://www.facebook.com/ifsulminascarmominas/?locale=pt_BR" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/ig-verde.png", link: "https://www.instagram.com/ifsuldeminascdm/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/linkedin-verde.png", link: "https://www.linkedin.com/school/if-sul-de-minas/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/yt-verde.png", link: "https://www.youtube.com/@TVIFSULDEMINAS" }
      ],
      imagemFinal: "https://portal.ifsuldeminas.edu.br/images/Assinatura_Email/ass_carmodeminas.png",
      setores: [
        { nome: "Selecione o Setor!", site: "#" },
        { nome: "CEAD", site: "https://portal.cdm.ifsuldeminas.edu.br/contato" },
        { nome: "CGP", site: "https://portal.cdm.ifsuldeminas.edu.br/contato" },
        { nome: "DAP", site: "https://portal.cdm.ifsuldeminas.edu.br/contato" },
        { nome: "DEPE", site: "https://portal.cdm.ifsuldeminas.edu.br/contato" },
        { nome: "Docente", site: "https://portal.cdm.ifsuldeminas.edu.br/servidores-contato/corpo-docente" },
        { nome: "NTI", site: "https://portal.cdm.ifsuldeminas.edu.br/contato" },
        { nome: "Secretaria", site: "https://portal.cdm.ifsuldeminas.edu.br/contato" },
        { nome: "SAE", site: "https://portal.cdm.ifsuldeminas.edu.br/contato" }
      ]
    },
    "Local 3": { // Inconfidentes
      logo: "https://portal.ifsuldeminas.edu.br/images/PDFs/comunicacao/logotipos/inconfidentes/inconfidentes-hor.png",
      endereco: "Praça Tiradentes, 416, Centro, Inconfidentes, MG, CEP: 37.576-000",
      site: "https://portal.ifs.ifsuldeminas.edu.br/",
      telefone: "(35) 3464-1200",
      redesSociais: [
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/fb-verde.png", link: "https://www.facebook.com/institutofederalcampusinconfidentes/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/ig-verde.png", link: "https://www.instagram.com/ifsuldeminasinconfidentes/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/linkedin-verde.png", link: "https://www.linkedin.com/school/if-sul-de-minas/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/x-verde.png", link: "https://x.com/IFInconfidentes" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/yt-verde.png", link: "https://www.youtube.com/channel/UCpgeZdVGTOMm7NyV9MvFALw" }
      ],
      imagemFinal: "https://portal.ifsuldeminas.edu.br/images/Assinatura_Email/ass_inconfidentes.png",
      setores: [
        { nome: "Selecione o Setor!", site: "#" },
        { nome: "Agroecologia", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/museu-natural" },
        { nome: "ASCOM", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/68-institucional/departamentos/165-ascom" },
        { nome: "Biblioteca", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/68-institucional/departamentos/109-biblioteca-afonso-arinos" },
        { nome: "Casa das Artes", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/casa-das-artes" },
        { nome: "CEAD", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/cead" },
        { nome: "COOPEAFI", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/68-institucional/departamentos/739-cooperativa" },
        { nome: "COPESE", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/68-institucional/departamentos/112-copese" },
        { nome: "CEXT", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/extensao" },
        { nome: "CPESQ", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/pesquisa" },
        { nome: "CGAE", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/68-institucional/departamentos/171-coordenacao-geral-de-assistencia-ao-educando" },
        { nome: "CGGP", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/68-institucional/departamentos/168-cgrh" },
        { nome: "Coordenação pedagógica", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/68-institucional/departamentos/190-coordenacao-pedagogica" },
        { nome: "DAP", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/dap-departamento-de-administracao-e-planejamento" },
        { nome: "DEN", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/den" },
        { nome: "DDE", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/dde" },        
        { nome: "Docente", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/servidores" }, 
        { nome: "Enfermaria", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/2-sem-categoria/1602-enfermaria" },
        { nome: "Gabinete", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/68-institucional/departamentos/166-gabinete" },
        { nome: "Herbário Institucional", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/herbario" },
        { nome: "Incetec", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/incubadora-de-empresas" },
        { nome: "Museu de História Natural Laércio Loures", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/museu-natural" },
        { nome: "NTI", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/nti" },
        { nome: "Restaurante Estudantil", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/component/content/article/68-institucional/departamentos/113-restaurante-estudantil" },
        { nome: "Secretaria dos Cursos Técnicos", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/secretaria-cursos-tecnicos" },
        { nome: "Secretaria dos Cursos Superiores", site: "https://portal.ifs.ifsuldeminas.edu.br/index.php/secretaria-cursos-superiores" }
      ]
    },
    "Local 4": { // Machado
      logo: "https://portal.ifsuldeminas.edu.br/images/PDFs/comunicacao/logotipos/machado/machado-hor.png",
      endereco: "Rodovia Machado - Paraguaçu, km 3, Bairro Santo Antônio, Machado, MG, CEP: 37.750-000",
      site: "https://portal.mch.ifsuldeminas.edu.br/",
      telefone: "(35) 3295-9700",
      redesSociais: [
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/fb-verde.png", link: "https://www.facebook.com/ifsuldeminasmachado" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/ig-verde.png", link: "https://www.instagram.com/ifsuldeminasmachado/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/linkedin-verde.png", link: "https://www.linkedin.com/school/if-sul-de-minas/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/yt-verde.png", link: "https://www.youtube.com/channel/UC2jUQb-eFTThXQqEWLHguJg" }
      ],
      imagemFinal: "https://portal.ifsuldeminas.edu.br/images/Assinatura_Email/ass_machado.png",
      setores: [
        { nome: "Selecione o Setor!", site: "#" },
        { nome: "ASCOM", site: "https://portal.mch.ifsuldeminas.edu.br/equipe" },
        { nome: "Assistência ao Ensino", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2504" },
        { nome: "Biblioteca", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2511" },
        { nome: "CGAE", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2513" },
        { nome: "CGAF", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2516" },
        { nome: "CGGP", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2515" },
        { nome: "Coordenação pedagógica", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2505" },
        { nome: "Coordenadoria de Compras e Contratos", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2519" },
        { nome: "Coordenadoria de Materiais e Patrimônio", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2518" },
        { nome: "CGPRO", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2517" },
        { nome: "CGPPI", site: "https://portal.mch.ifsuldeminas.edu.br/equipe-cgppi" },
        { nome: "Coordenadoria Geral de Extensão", site: "https://portal.mch.ifsuldeminas.edu.br/fale-conosco" },
        { nome: "Coordenadoria Geral de Infrestruturas e Serviços", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2520" },
        { nome: "Coordenadoria de Finanças e Contabilidade", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2523" },
        { nome: "Coordenadoria de Manutenção e Infraestrutura", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2524" },        
        { nome: "Docente", site: "https://portal.mch.ifsuldeminas.edu.br/docente-cotatos" }, 
        { nome: "Gabinete", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2510" },
        { nome: "NTI", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2502" },
        { nome: "Secretaria de Registros Acadêmicos", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2503" },
        { nome: "Transporte", site: "https://portal.mch.ifsuldeminas.edu.br/equipes?id=2522" }
      ]
    },
    "Local 5": { // Muzambinho
      logo: "https://portal.ifsuldeminas.edu.br/images/PDFs/comunicacao/logotipos/muzambinho/muzambinho-hor.png",
      endereco: "Estrada de Muzambinho, km 35, Bairro Morro Preto, Muzambinho, MG, CEP: 37.890-000",
      site: "https://www.muz.ifsuldeminas.edu.br/",
      telefone: "(35) 3571-5051",
      redesSociais: [
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/fb-verde.png", link: "https://www.facebook.com/ifsuldeminasmuzambinho/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/ig-verde.png", link: "https://www.instagram.com/ifsuldeminas__muzambinho/?hl=pt-br" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/linkedin-verde.png", link: "https://www.linkedin.com/school/if-sul-de-minas/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/x-verde.png", link: "https://x.com/ifmuzambinho" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/yt-verde.png", link: "https://www.youtube.com/c/IFSULDEMINASCampusMuzambinho" }
      ],
      imagemFinal: "https://portal.ifsuldeminas.edu.br/images/Assinatura_Email/ass_muzambinho.png",
      setores: [
        { nome: "Selecione o Setor!", site: "#" },
        { nome: "Abatedouro de Frangos e Coelhos", site: "https://www.muz.ifsuldeminas.edu.br/setores/2291-abatedouro-de-frangos-e-coelhos" },
        { nome: "Almoxarifado", site: "https://www.muz.ifsuldeminas.edu.br/setores/1585-setor-almoxarifado" },
        { nome: "Apicultura", site: "https://www.muz.ifsuldeminas.edu.br/setores/1588-setor-apicultura" },
        { nome: "Assessoria de Normas e Legislação", site: "https://www.muz.ifsuldeminas.edu.br/setores/1591-setor-assessoria-normas-legislacao" },
        { nome: "ASCOM", site: "https://www.muz.ifsuldeminas.edu.br/comunicacao" },
        { nome: "Atendimento ao Educando", site: "https://www.muz.ifsuldeminas.edu.br/setores/2298-atendimento-ao-educando" },
        { nome: "Avicultura de Corte", site: "https://www.muz.ifsuldeminas.edu.br/setores/2282-avicultura-de-corte" },
        { nome: "Avicultura de Postura", site: "https://www.muz.ifsuldeminas.edu.br/setores/2283-avicultura-de-postura" },
        { nome: "Biblioteca Monteiro Lobato e Biblioteca Setorial de Educação Física do CeCAES", site: "https://www.muz.ifsuldeminas.edu.br/biblioteca" },
        { nome: "Bovinocultura de Corte", site: "https://www.muz.ifsuldeminas.edu.br/setores/2289-bovinocultura-de-corte" },
        { nome: "Bovinocultura de Leite", site: "https://www.muz.ifsuldeminas.edu.br/setores/2288-bovinocultura-de-leite" },
        { nome: "Cadastro, Lotação e Pagamento", site: "https://www.muz.ifsuldeminas.edu.br/setores/2272-cadastro-lotacao-e-pagamento" },
        { nome: "Cafeicultura", site: "https://www.muz.ifsuldeminas.edu.br/setores/2278-cafeicultura" },
        { nome: "Caprinocultura de Leite", site: "https://www.muz.ifsuldeminas.edu.br/setores/1655-caprinocultura-de-leite" },
        { nome: "Cães", site: "https://www.muz.ifsuldeminas.edu.br/setores/2286-caes" },
        { nome: "CEAD", site: "https://www.muz.ifsuldeminas.edu.br/cead" },
        { nome: "CEAM", site: "https://www.muz.ifsuldeminas.edu.br/ceam" },
        { nome: "CELIN", site: "https://www.muz.ifsuldeminas.edu.br/celin" },
        { nome: "CEMEFEL", site: "https://www.muz.ifsuldeminas.edu.br/setores/1593-setor-cemefel" },
        { nome: "Centro de Memórias", site: "https://www.muz.ifsuldeminas.edu.br/centro-de-memorias" },
        { nome: "CFIC", site: "https://www.muz.ifsuldeminas.edu.br/coordenadorias/2303-coordenadoria-de-formacao-inicial-e-continuada" },
        { nome: "CGAE", site: "https://www.muz.ifsuldeminas.edu.br/cgae" },
        { nome: "CGAF", site: "https://www.muz.ifsuldeminas.edu.br/cgaf" },
        { nome: "CGE", site: "https://www.muz.ifsuldeminas.edu.br/cge" },
        { nome: "CGEx", site: "https://www.muz.ifsuldeminas.edu.br/projetos-de-extensao" },
        { nome: "CGGP", site: "https://www.muz.ifsuldeminas.edu.br/cggp" },
        { nome: "CGIS", site: "https://www.muz.ifsuldeminas.edu.br/cgis" },
        { nome: "CGP", site: "https://www.muz.ifsuldeminas.edu.br/cgp" },
        { nome: "CGPPI", site: "https://www.muz.ifsuldeminas.edu.br/cgppi" },
        { nome: "Compras, Contratos e Convênios", site: "https://www.muz.ifsuldeminas.edu.br/setores/2205-compras-contratos-e-convenios" },
        { nome: "Contabilidade", site: "https://www.muz.ifsuldeminas.edu.br/setores/2203-setor-contabilidade" },
        { nome: "COPESE", site: "https://www.muz.ifsuldeminas.edu.br/setores/1604-setor-copese" },
        { nome: "COOPAM", site: "https://www.muz.ifsuldeminas.edu.br/setores/1602-setor-cooperativa" },
        { nome: "Coordenadoria de Inovação", site: "https://www.muz.ifsuldeminas.edu.br/setores/2946-coordenadoria-de-inovacao" },
        { nome: "Coordenadoria de Pesquisa", site: "https://www.muz.ifsuldeminas.edu.br/setores/2944-coordenadoria-de-pesquisa" },
        { nome: "Coordenadoria de Pós-Graduação", site: "https://www.muz.ifsuldeminas.edu.br/setores/2945-coordenadoria-de-pos-graduacao" },
        { nome: "Coordenadoria de Registros Acadêmicos", site: "https://www.muz.ifsuldeminas.edu.br/secretaria" },
        { nome: "Coordenadorias dos Cursos", site: "https://www.muz.ifsuldeminas.edu.br/setores/2940-coordenadorias-dos-cursos" },
        { nome: "Cunicultura", site: "https://www.muz.ifsuldeminas.edu.br/setores/2284-cunicultura" },
        { nome: "DAP", site: "https://www.muz.ifsuldeminas.edu.br/setores/1660-dap" },
        { nome: "DDE", site: "https://www.muz.ifsuldeminas.edu.br/setores/1606-setor-dde" },
        { nome: "DEn", site: "https://www.muz.ifsuldeminas.edu.br/setores/2939-diretoria-de-ensino" },
        { nome: "Desenvolvimento e Capacitação", site: "https://www.muz.ifsuldeminas.edu.br/setores/2273-desenvolvimento-e-capacitacao" },
        { nome: "Diretor-Geral do IFSULDEMINAS - Campus Muzambinho", site: "https://www.muz.ifsuldeminas.edu.br/setores/2080-diretor" },        
        { nome: "Docente", site: "https://www.muz.ifsuldeminas.edu.br/corpo-docente" }, 
        { nome: "Esportes, Lazer, Cultura e Artes", site: "https://www.muz.ifsuldeminas.edu.br/setores/2299-esportes-lazer-cultura-e-artes" },
        { nome: "Estação de Tratamento de Água", site: "https://www.muz.ifsuldeminas.edu.br/setores/3058-estacao-de-tratamento-de-agua" },
        { nome: "Execução Orçamentária e Financeira", site: "https://www.muz.ifsuldeminas.edu.br/setores/2206-execucao-orcamentaria-e-financeira" },
        { nome: "Fazenda Experimental de Guaxupé", site: "https://www.muz.ifsuldeminas.edu.br/fazenda-em-guaxupe" },
        { nome: "Fiscalização e Prestação de Serviços", site: "https://www.muz.ifsuldeminas.edu.br/setores/1609-setor-fiscalizacao" },
        { nome: "Fruticultura", site: "https://www.muz.ifsuldeminas.edu.br/setores/2277-fruticultura" },
        { nome: "Gabinete", site: "https://www.muz.ifsuldeminas.edu.br/setores/1610-setor-gabinete-do-diretor" },
        { nome: "Gestão Operacional da Terceirização", site: "https://www.muz.ifsuldeminas.edu.br/setores/2271-gestao-operacional-da-terceirizacao" },
        { nome: "Industrialização do Café", site: "https://www.muz.ifsuldeminas.edu.br/setores/2290-industrializacao-do-cafe" },
        { nome: "Jardinagem e Paisagismo", site: "https://www.muz.ifsuldeminas.edu.br/setores/2279-jardinagem-e-paisagismo" },
        { nome: "Laboratório de Bromatologia e Água", site: "https://www.muz.ifsuldeminas.edu.br/lab-bromatologia" },
        { nome: "Laboratório de Solos e Tecido Vegetal", site: "https://www.muz.ifsuldeminas.edu.br/lab-solos" },
        { nome: "Laboratórios de Produção", site: "https://www.muz.ifsuldeminas.edu.br/laboratorios-de-producao" },
        { nome: "Mecanização Agrícola", site: "https://www.muz.ifsuldeminas.edu.br/mecanizacao-agricola" },
        { nome: "NAPNE", site: "https://www.muz.ifsuldeminas.edu.br/napne" },
        { nome: "NIPE", site: "https://www.muz.ifsuldeminas.edu.br/nucleo-institucional-de-pesquisa-e-extensao" },
        { nome: "NIT", site: "https://www.muz.ifsuldeminas.edu.br/setores/1747-nit-elitt" },
        { nome: "NTI", site: "https://www.muz.ifsuldeminas.edu.br/setores-nti" },
        { nome: "Obras", site: "https://www.muz.ifsuldeminas.edu.br/setores/2952-setor-de-obras" },
        { nome: "Olericultura", site: "https://www.muz.ifsuldeminas.edu.br/setores/2280-olericultura" },
        { nome: "Orientação Educacional", site: "https://www.muz.ifsuldeminas.edu.br/setores/1619-setor-orientacao-educacional" },
        { nome: "Ovinocultura", site: "https://www.muz.ifsuldeminas.edu.br/setores/2285-ovinocultura" },
        { nome: "Patrimônio", site: "https://www.muz.ifsuldeminas.edu.br/setores/2275-patrimonio" },
        { nome: "Pesquisadora Institucional", site: "https://www.muz.ifsuldeminas.edu.br/setores/2235-pesquisadora-institucional" },
        { nome: "Pregoeiro", site: "https://www.muz.ifsuldeminas.edu.br/setores/2202-pregoeiro" },
        { nome: "Produção Agrícola", site: "https://www.muz.ifsuldeminas.edu.br/setores/2936-setores-de-producao-agricola" },
        { nome: "Produção Agroindustrial", site: "https://www.muz.ifsuldeminas.edu.br/setores/1584-producao-agroindustrial" },
        { nome: "Produção Animal", site: "https://www.muz.ifsuldeminas.edu.br/producao-animal" },
        { nome: "Refeitório, Alimentação e Nutrição", site: "https://www.muz.ifsuldeminas.edu.br/setores/1625-setor-refeitorio-alimentacao-e-nutricao" },
        { nome: "SAICE", site: "https://www.muz.ifsuldeminas.edu.br/saice" },
        { nome: "Serviços Gerais", site: "https://www.muz.ifsuldeminas.edu.br/setores/2951-setor-de-servicos-gerais" },
        { nome: "Suinocultura", site: "https://www.muz.ifsuldeminas.edu.br/setores/2287-suinocultura" },
        { nome: "Transporte", site: "https://www.muz.ifsuldeminas.edu.br/setores/2950-setor-de-transporte" },
        { nome: "Unidade CeCaes", site: "https://www.muz.ifsuldeminas.edu.br/setores/1596-setor-cecaes" },
        { nome: "Unidade Dr. José Januário Magalhães", site: "https://www.muz.ifsuldeminas.edu.br/setores/1634-unidade-dr-jose-januario-magalhaes" },
        { nome: "Usina Hidroelétrica", site: "https://www.muz.ifsuldeminas.edu.br/setores/1635-usina-hidreletrica" },
        { nome: "Vigilância Patrimonial", site: "https://www.muz.ifsuldeminas.edu.br/setores/2953-setor-de-vigilancia-patrimonial" },
        { nome: "Viveiro Florestal", site: "https://www.muz.ifsuldeminas.edu.br/viveiro-florestal" }
      ]
    },
    "Local 6": { // Passos
      logo: "https://portal.ifsuldeminas.edu.br/images/PDFs/comunicacao/logotipos/passos/passos-hor.png",
      endereco: "Rua da Penha, 290, Bairro Penha II,Passos, MG, CEP: 37903-070",
      site: "https://portal.pas.ifsuldeminas.edu.br/",
      telefone: "(35) 3526-4856",
      redesSociais: [
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/fb-verde.png", link: "https://www.facebook.com/campuspassos/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/ig-verde.png", link: "https://www.instagram.com/ifsuldeminascampuspassos/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/linkedin-verde.png", link: "https://www.linkedin.com/school/if-sul-de-minas/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/yt-verde.png", link: "https://www.youtube.com/channel/UC73UAcaqQqVwu9m6ZACOaDw" }
      ],
      imagemFinal: "https://portal.ifsuldeminas.edu.br/images/Assinatura_Email/ass_passos.png",
      setores: [
        { nome: "Selecione o Setor!", site: "#" },
        { nome: "Almoxarifado e Patrimônio", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "ASCOM", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "Assistência ao Educando", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "Atendimento Multidisciplinar", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "Biblioteca", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "Compras e Licitações", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "Coordenadoria de Gestão de Pessoas/Gabinete", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "Coordenadoria de Infraestrutura, Transporte e Serviços", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "Coordenadoria de Laboratórios", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "Coordenadoria Orçamentária, Financeira e Contábil", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },        
        { nome: "Docente", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato/corpo-docente" }, 
        { nome: "Gestão de Contratos", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "NTI", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" },
        { nome: "SERPEX", site: "https://portal.pas.ifsuldeminas.edu.br/servidores-contato" }
      ]
    },
    "Local 7": { // Poços de Caldas
      logo: "https://portal.ifsuldeminas.edu.br/images/PDFs/comunicacao/logotipos/pocosdecaldas/pocos-de-caldas-hor.png",
      endereco: "Av. Dirce Pereira Rosa, 300, Bairro Jardim Esperança, Poços de Caldas, MG, CEP: 37713-100",
      site: "https://portal.pcs.ifsuldeminas.edu.br/",
      telefone: "(35) 3697-4950",
      redesSociais: [
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/fb-verde.png", link: "https://www.facebook.com/ifpocosoficial" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/ig-verde.png", link: "https://www.instagram.com/ifpocosoficial/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/linkedin-verde.png", link: "https://www.linkedin.com/company/ifpocosoficial/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/x-verde.png", link: "https://x.com/ifpocosoficial" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/yt-verde.png", link: "https://www.youtube.com/ifpocosoficial" }
      ],
      imagemFinal: "https://portal.ifsuldeminas.edu.br/images/Assinatura_Email/ass_pocosdecaldas.png",
      setores: [
        { nome: "Selecione o Setor!", site: "#" },
        { nome: "ASCOM", site: "https://portal.pcs.ifsuldeminas.edu.br/comunicacao" },
        { nome: "Biblioteca", site: "https://portal.pcs.ifsuldeminas.edu.br/biblioteca" },
        { nome: "CAAD", site: "https://portal.pcs.ifsuldeminas.edu.br/ensino-educacao-distancia-pagina-principal/secretaria" },
        { nome: "CCLC", site: "https://portal.pcs.ifsuldeminas.edu.br/administracao-e-planejamento/274-administracao-planejamento/2100-licitacoes-contratos-pagina-inicial" },
        { nome: "CEL", site: "https://portal.pcs.ifsuldeminas.edu.br/" },
        { nome: "CeaD", site: "https://portal.pcs.ifsuldeminas.edu.br/" },
        { nome: "CEN", site: "https://portal.pcs.ifsuldeminas.edu.br/ensino-educacao-distancia-pagina-principal" },
        { nome: "CISAP", site: "https://portal.pcs.ifsuldeminas.edu.br/diretoria-de-administracao-e-planejamento-dap/coordenadoria-de-administracao-e-financas-caf/infraestrutura-e-servicos" },
        { nome: "COES", site: "https://portal.pcs.ifsuldeminas.edu.br/noticias-nao-publicadas/3785-napne-campus-pocos" },
        { nome: "COEX", site: "https://portal.pcs.ifsuldeminas.edu.br/extensao-menu-campus" },
        { nome: "COFC", site: "https://portal.pcs.ifsuldeminas.edu.br/diretoria-de-administracao-e-planejamento-dap/coordenadoria-de-administracao-e-financas-caf/financeiro-e-contabil" },
        { nome: "CPAE", site: "https://portal.pcs.ifsuldeminas.edu.br/ensino-educacao-distancia-pagina-principal/setor-de-assistencia-ao-educando-sae" },
        { nome: "CPPI", site: "https://portal.pcs.ifsuldeminas.edu.br/pesquisa-pagina-principal" },
        { nome: "DAP", site: "https://portal.pcs.ifsuldeminas.edu.br/" },
        { nome: "DDE", site: "https://portal.pcs.ifsuldeminas.edu.br/" },        
        { nome: "Docente", site: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTqIDpZYSwx8Eexmu64jVIMWwCHfrbOtaH8aoBPyqPjaWYf1qk45osWTLSFOX1eS150Ii3-GMTv2W3N/pubhtml?gid=1688216364&single=true" }, 
        { nome: "Gabinete e Gestão de Pessoas", site: "https://portal.pcs.ifsuldeminas.edu.br/gabinete-gestao-pessoas" },
        { nome: "NAPNE", site: "https://portal.pcs.ifsuldeminas.edu.br/noticias-nao-publicadas/3785-napne-campus-pocos" },
        { nome: "NTI", site: "https://portal.pcs.ifsuldeminas.edu.br/tecnologia-informacao-nti" },
        { nome: "Técnicos de Laboratório", site: "https://portal.pcs.ifsuldeminas.edu.br/ensino-educacao-distancia-pagina-principal/laboratorios" }
      ]
    },
    "Local 8": { // Pouso Alegre
      logo: "https://portal.ifsuldeminas.edu.br/images/PDFs/comunicacao/logotipos/pousoalegre/pouso-alegre-hor.png",
      endereco: "Av. Maria da Conceição Santos, 900, Bairro Parque Real, Pouso Alegre, MG, CEP: 37560-260",
      site: "https://portal.poa.ifsuldeminas.edu.br/",
      telefone: "(35) 3427-6600",
      redesSociais: [
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/fb-verde.png", link: "https://www.facebook.com/campuspousoalegre/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/ig-verde.png", link: "https://www.instagram.com/ifsuldeminaspousoalegre/?hl=pt-br" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/linkedin-verde.png", link: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/linkedin_ok.png" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/yt-verde.png", link: "https://www.youtube.com/channel/UC73UAcaqQqVwu9m6ZACOaDw" }
      ],
      imagemFinal: "https://portal.ifsuldeminas.edu.br/images/Assinatura_Email/ass_pousoalegre.png",
      setores: [
        { nome: "Selecione o Setor!", site: "#" },        
        { nome: "ASCOM", site: "https://portal.poa.ifsuldeminas.edu.br/comunicacao" },        
        { nome: "Biblioteca", site: "https://portal.poa.ifsuldeminas.edu.br/diret-de/diret-de-2?view=article&layout=edit&id=2662" },        
        { nome: "CAE", site: "https://portal.poa.ifsuldeminas.edu.br/diret-de/diret-de-2?view=article&layout=edit&id=2661" },        
        { nome: "Coordenadoria Contábil, Financeira e Orçamentária", site: "https://portal.poa.ifsuldeminas.edu.br/dap/coord-finaceira" },        
        { nome: "Coordenadoria de Compras, Licitações e Contratos", site: "https://portal.poa.ifsuldeminas.edu.br/dap/coord-compras" },        
        { nome: "Coordenadoria de Infraestrutura e Transportes", site: "https://portal.poa.ifsuldeminas.edu.br/dap/coord-infraestrutura" },   
        { nome: "DAP", site: "https://portal.poa.ifsuldeminas.edu.br/dap" },        
        { nome: "DDE", site: "https://portal.poa.ifsuldeminas.edu.br/diret-de" },        
        { nome: "Docente", site: "https://portal.poa.ifsuldeminas.edu.br/servidores-contato/corpo-docente" },        
        { nome: "Gabinete da Direção", site: "https://portal.poa.ifsuldeminas.edu.br/diretoria-geral/gabinete-da-direcao" },        
        { nome: "Gestão de Pessoas", site: "https://portal.poa.ifsuldeminas.edu.br/diretoria-geral/coordenadoria-de-gestao-de-pessoas" },
        { nome: "NTI", site: "https://portal.poa.ifsuldeminas.edu.br/diretoria-geral/nti" },        
        { nome: "Secretaria", site: "https://portal.poa.ifsuldeminas.edu.br/diret-de/diret-de-2?view=article&layout=edit&id=2231" }
      ]
    },
    "Local 9": { // Três Corações
      logo: "https://portal.ifsuldeminas.edu.br/images/PDFs/comunicacao/logotipos/trescoracoes/IFSULDEMINAS_Tres-Coracoes-aplica%C3%A7%C3%B5es-horizontais-01.png",
      endereco: "Rua Coronel Edgar Cavalcanti de Albuquerque, 61, Bairro Chácara das Rosas, Três Corações, MG, CEP: 37417-158",
      site: "https://portal.tco.ifsuldeminas.edu.br/",
      telefone: "(35) 3239-9494",
      redesSociais: [
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/fb-verde.png", link: "https://www.facebook.com/IFSULDEMINAS" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/ig-verde.png", link: "https://www.instagram.com/ifsuldeminas/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/linkedin-verde.png", link: "https://www.linkedin.com/school/if-sul-de-minas/" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/FotoBranca.png", link: "#" },
        { logo: "https://portal.ifsuldeminas.edu.br/images/comunica%C3%A7%C3%A3o/Icones/yt-verde.png", link: "https://www.youtube.com/@TVIFSULDEMINAS" }
      ],
      imagemFinal: "https://portal.ifsuldeminas.edu.br/images/Assinatura_Email/ass_trescoracoes.png",
      setores: [
        { nome: "Selecione o Setor!", site: "#" },  
        { nome: "Biblioteca", site: "https://portal.tco.ifsuldeminas.edu.br/portal-do-aluno/187-o-campus/1453-biblioteca" },        
        { nome: "CIEC", site: "https://portal.tco.ifsuldeminas.edu.br/horarios-dos-setores" },        
        { nome: "CGE", site: "https://sites.google.com/ifsuldeminas.edu.br/iftrescoracoesdde/cge?authuser=0" },      
        { nome: "Coordenadoria de Administração e Planejamento", site: "https://portal.tco.ifsuldeminas.edu.br/horarios-dos-setores" },        
        { nome: "Coordenadoria de Gestão de Pessoas", site: "https://portal.tco.ifsuldeminas.edu.br/horarios-dos-setores" },        
        { nome: "DDE", site: "https://sites.google.com/ifsuldeminas.edu.br/iftrescoracoesdde/p%C3%A1gina-inicial?authuser=2" },        
        { nome: "Diretor Geral", site: "https://portal.tco.ifsuldeminas.edu.br/direcao" },        
        { nome: "Diretoria de Administração e Planejamento", site: "https://portal.tco.ifsuldeminas.edu.br/direcao" },        
        { nome: "Diretoria de Ensino, Pesquisa e Extensão", site: "https://portal.tco.ifsuldeminas.edu.br/direcao" },        
        { nome: "Docente", site: "https://portal.tco.ifsuldeminas.edu.br/servidores-contato/corpo-docente" },    
        { nome: "NAPNE", site: "https://portal.tco.ifsuldeminas.edu.br/napne2" },         
        { nome: "NTI", site: "https://portal.tco.ifsuldeminas.edu.br/nti" },        
        { nome: "Secretaria Escolar", site: "https://sites.google.com/ifsuldeminas.edu.br/iftrescoracoesdde/secretaria?authuser=0" },        
        { nome: "Setor de Apoio do Educando", site: "https://portal.tco.ifsuldeminas.edu.br/portal-do-aluno/198-portal-do-aluno/1518-horario-do-setor-de-assistencia-ao-educando" }
      ]
    }
  };
  return locais[localTrabalho];
}

// Função para solicitar permissão e modificar a assinatura do Gmail
function salvarAssinatura(assinaturaHtml) {
  try {
    const userEmail = Session.getActiveUser().getEmail();
    Gmail.Users.Settings.SendAs.update({ signature: assinaturaHtml }, userEmail, userEmail);
    return true;
  } catch (e) {
    Logger.log('Erro ao modificar a assinatura: ' + e.message);
    return false;
  }
}